SUPABASE_URL = "https://eahmlurxrbnldaisvowx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhaG1sdXJ4cmJubGRhaXN2b3d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1MTY0OTgsImV4cCI6MjA5NDA5MjQ5OH0.dACTOMJZVXlKuByHB9NcjYCFLnVCAnQTW_LW3uUwkKg"
